### PR TITLE
Don't restart memcached on a config change

### PR DESCRIPTION
**Pull request by eabbott**
I don't think it's the right thing to do to restart memcached via puppet on a config change. During standard maintenance it'd be nice to have the option to change the config w/o having brief downtime.

For instance we're going to reduce the RAM allocated for caching a bit and introduce a new cluster. That will involve one brief downtime while memcached restarts, and then a "flush" as the new cluster is brought into play. It'd be nicer not to have that restart.

Technically we could get around that config restart by using a branch env on the new servers. Then when the branch is merged into master after the switch to new servers there'd be no restart since the config file hadn't changed. But if we did that, what's the point of the auto-restart? To make things easier in qa which has fewer servers anyway?

### CODE REVIEW

**Comment by eabbott** [comment]
Good suggestion, I've updated and rebased to keep the branch clean.

**Comment by craigtracey** [comment]
You only need the conditional for the affirmative case.

**Comment by eabbott** [comment]
We need the ordering so the service knows to wait for the config file right?

**Comment by craigtracey** [comment]
Sorry for the terseness of my previous comment - I was on the bus.

The point I am trying to make is that this will not do what, I think, you are trying to do.  If I understand correctly, you want to make the service restart a class parameter.

If this is indeed the case, you want to be sure that the configuration file is managed prior to the service, and your File -> Service syntax (without the conditional) should help with that.

However, your change is still disabling the service restart, regardless of the value of $svc_restart.  The $svc_restart parameter should be used to set which files the service should watch.  In the affirmative, it should watch the config file an in the negative it should watch nothing.

**Comment by eabbott** [comment]
http://docs.puppetlabs.com/puppet/2.7/reference/lang_relationships.html#chaining-arrows
Not entirely sure I follow you Craig. I'm attempting to use the chaining arrows as described in the previous link.

**Comment by craigtracey** [comment]
OK, yes you are correct.  This should work then, 

Both of those chains looked the same to me... as ->'s; not a ~> and ->.

You might just want to comment that as it is easily missed.

**Comment by eabbott** [comment]
I missed the distinction right away as well, I like the idea of calling out the difference with a comment. Done.

**Comment by tmclaugh** [comment]
Eric, please submit this upstream too. 

Also, open a PR against puppet-deploy to add svc_restart to any place we declare the men cached class resource. I want to merge both changes at once.

**Pull request merged**
